---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: magi-system-node
  namespace: limited
  labels:
    app: magi-system
spec:
  selector:
    matchLabels:
      name: magi-system
  template:
    metadata:
      labels:
        name: magi-system
    spec:
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - image: registry-10-231-0-208.nip.io/mfranzil/magi-system:latest
        command:
          - "/app/init_node.sh"
        imagePullPolicy: IfNotPresent
        name: magi-system
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_ADMIN"] # add the capabilities you need https://man7.org/linux/man-pages/man7/capabilities.7.html
          runAsUser: 0 # run as root
      restartPolicy: Always # we want to be intentional about running this pod
      hostIPC: true # Use the host's ipc namespace https://www.man7.org/linux/man-pages/man7/ipc_namespaces.7.html
      hostNetwork: true # Use the host's network namespace https://www.man7.org/linux/man-pages/man7/network_namespaces.7.html
      hostPID: true # Use the host's pid namespace https://man7.org/linux/man-pages/man7/pid_namespaces.7.html
