apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "connect"
spec:
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
    - index: 0
      type: "sock"
#    selectors:
#      - matchBinaries:
#        - operator: In
#          values:
#          - "/usr/bin/containerd"
  - call: "sys_mkdirat"
    syscall: true
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "string"
    - index: 2
      type: "int"
#    selectors:
#      - matchBinaries:
#        - operator: In
#          values:
#          - "/usr/bin/containerd"
#  - call: "tcp_close"
#    syscall: false
#    args:
#    - index: 0
#      type: "sock"
#  - call: "tcp_sendmsg"
#    syscall: false
#    args:
#    - index: 0
#      type: "sock"
#    - index: 2
#      type: int
#  - call: "sys_getsockname"
#    syscall: true
#    args:
#    - index: 0
#      type: "int"
#    - index: 1
#      type: "sock"
#    - index: 2
#      type: "size_t"
