apiVersion: v1
kind: Pod
metadata:
  name: httpd
  namespace: limited
spec:
  containers:
  - name: default
    image: $REGISTRY_IP_DOMAIN/mfranzil/obese-httpd:1
  imagePullSecrets:
  - name: regcred

