apiVersion: v1
kind: Pod
metadata:
  name: httpd
  namespace: limited
spec:
  containers:
  - name: default
    image: registry-10-231-0-208.nip.io/mfranzil/obese-httpd:1
  imagePullSecrets:
  - name: regcred

