apiVersion: v1
kind: Pod
metadata:
  name: pts 
  namespace: limited
spec:
  containers:
  - name: default
    image: $REGISTRY_IP_DOMAIN/mfranzil/pts:latest
    args: ["/phoronix-test-suite/phoronix-test-suite", "shell"]
    #args: ["/phoronix-test-suite/phoronix-test-suite", "benchmark", "build-linux-kernel"]
    imagePullPolicy: Always
  # nodeSelector:
    # kubernetes.io/hostname: $SELECTED_NODE_NAME 
  imagePullSecrets:
  - name: regcred
