apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - image: alqutami/rtmp-hls:latest-alpine
      name: rtmp
    - image: linuxserver/ffmpeg
      name: ffmpeg
      args: ["-re","-i","/files/movie.mp4","-c:v","libx264","-c:a","aac","-f","flv","rtmp://localhost:1935/live/stream"]
      volumeMounts:
      - name: files
        mountPath: /files
  volumes:
  - name: files
    hostPath:
      path: /files
---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: test
  ports:
    - protocol: TCP
      name: rtmp
      port: 1935
      targetPort: 1935
      nodePort: 30001
    - protocol: TCP
      name: hls
      port: 8080
      targetPort: 8080
      nodePort: 30002
