apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-1
  namespace: limited
spec:
  replicas: 8
  selector:
    matchLabels:
      app: test-1
  template:
    metadata:
      labels:
        app: test-1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - test-1
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: test-1
        image: pytorch/pytorch:2.7.1-cuda11.8-cudnn9-runtime
        imagePullPolicy: Always
        
    